import { APP_BASE_HREF } from '@angular/common';
import { CommonEngine } from '@angular/platform-server';
import * as express from 'express';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import 'zone.js/node';

// The AppServerModule is the entry point for the server-side rendering.
// It is typically generated by the Angular CLI in the 'dist' folder.
// We assume the build output is in 'dist/<project-name>/browser' and 'dist/<project-name>/server'.
// Since the project name is not provided, we use a generic path.
// In a real application, replace 'browser' with the actual project name's browser output folder.
const DIST_FOLDER = join(process.cwd(), 'dist/browser');

// The main server bundle is expected to be in the server output folder.
// The file is usually named 'main.server.js' or similar.
// We use a dynamic import to load the server bundle.
const bootstrap = () => import('./dist/server/main.js');

// The Express app is created in a function to allow for easy testing and deployment.
export function app(): express.Express {
  const server = express();
  const indexHtml = existsSync(join(DIST_FOLDER, 'index.original.html'))
    ? 'index.original.html'
    : 'index.html';

  const commonEngine = new CommonEngine();

  server.set('view engine', 'html');
  server.set('views', DIST_FOLDER);

  // Serve static files from /browser
  server.get('*.*', express.static(DIST_FOLDER, {
    maxAge: '1y'
  }));

  // All regular routes use the Universal engine
  server.get('*', (req, res, next) => {
    const { protocol, originalUrl, baseUrl, headers } = req;

    bootstrap()
      .then(module => {
        commonEngine.render({
          bootstrap: module.default,
          documentFilePath: join(DIST_FOLDER, indexHtml),
          url: `${protocol}://${headers.host}${originalUrl}`,
          publicPath: DIST_FOLDER,
          providers: [{ provide: APP_BASE_HREF, useValue: baseUrl }],
        })
        .then(html => res.send(html))
        .catch(err => next(err));
      })
      .catch(err => next(err));
  });

  return server;
}

function run(): void {
  const port = process.env['PORT'] || 4000;

  // Start up the Node server
  const server = app();
  server.listen(port, () => {
    console.log(`Node Express server listening on http://localhost:${port}`);
  });
}

// Webpack will replace 'require' with '__webpack_require__'
// '__non_webpack_require__' is a proxy to Node 'require'
// The below code is to ensure that the server bundle is loaded correctly
declare const __non_webpack_require__: NodeRequire;
const mainModule = __non_webpack_require__.main;
const moduleFilename = mainModule && mainModule.filename || '';
if (moduleFilename === __filename || moduleFilename.includes('iisnode')) {
  run();
}